// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGVE_api.Context;

#nullable disable

namespace SGVEapi.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20230616232503_SeedSGVEDataTable")]
    partial class SeedSGVEDataTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SGVE_api.Models.Endereco", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_ENDERECO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id"));

                    b.Property<string>("bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("V_BAIRRO");

                    b.Property<int>("cep")
                        .HasMaxLength(8)
                        .HasColumnType("int")
                        .HasColumnName("I_CEP");

                    b.Property<string>("cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("V_CIDADE");

                    b.Property<string>("codigoIBGE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("V_CD_IBGE");

                    b.Property<string>("complemento")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("V_COMPLEMENTO");

                    b.Property<string>("logradouro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("V_LOGRADOURO");

                    b.Property<string>("tipoCep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("V_TIPO_CEP");

                    b.Property<string>("uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("V_UF");

                    b.HasKey("id");

                    b.ToTable("TB_ENDERECO");

                    b.HasData(
                        new
                        {
                            id = 1L,
                            bairro = "Jardim Novo Horizonte",
                            cep = 13188270,
                            cidade = "Hortolândia",
                            codigoIBGE = "3519071",
                            complemento = "",
                            logradouro = "Rua João de Camargo",
                            tipoCep = "1",
                            uf = "SP"
                        },
                        new
                        {
                            id = 2L,
                            bairro = "Piedade",
                            cep = 12285815,
                            cidade = "Caçapava",
                            codigoIBGE = "3508504",
                            complemento = "",
                            logradouro = "Rua Capitão Mário Raymundo da Silva",
                            tipoCep = "1",
                            uf = "SP"
                        },
                        new
                        {
                            id = 3L,
                            bairro = "Jardim Shangrilá (Zona Norte)",
                            cep = 2990250,
                            cidade = "São Paulo",
                            codigoIBGE = "3550308",
                            complemento = "",
                            logradouro = "Travessa João da Baiana",
                            tipoCep = "1",
                            uf = "SP"
                        });
                });

            modelBuilder.Entity("SGVE_api.Models.Funcionario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_FUNCIONARIO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Celular")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("V_CELULAR");

                    b.Property<string>("Complemento_Endereco")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("V_COMPLEMENTO");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("V_CPF");

                    b.Property<string>("DDD_Celular")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("V_DDD_CELULAR");

                    b.Property<string>("DDD_Telefone")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("V_DDD_TELEFONE");

                    b.Property<DateTime>("Data_Cadastro")
                        .HasMaxLength(20)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<DateTime?>("Data_Desligamento")
                        .HasMaxLength(20)
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_DESLIGAMENTO");

                    b.Property<DateTime>("Data_Nascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_NASCIMENTO");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("V_EMAIL");

                    b.Property<int>("Id_Cargo")
                        .HasMaxLength(15)
                        .HasColumnType("int")
                        .HasColumnName("FK_ID_CARGO");

                    b.Property<int>("Id_Endereco")
                        .HasMaxLength(15)
                        .HasColumnType("int")
                        .HasColumnName("FK_ID_ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("V_NOME");

                    b.Property<string>("Numero_Endereco")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("I_NUM_ENDERECO");

                    b.Property<string>("Rg")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("V_RG");

                    b.Property<string>("Senha")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("V_SENHA");

                    b.Property<string>("Telefone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("V_TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("TB_FUNCIONARIO");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            Cpf = "11122233344",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCargo = 0,
                            IdEndereco = 0,
                            Nome = "João"
                        },
                        new
                        {
                            Id = 3L,
                            Cpf = "55566677799",
                            DataCadastro = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataNascimento = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCargo = 0,
                            IdEndereco = 0,
                            Nome = "Pedro"
                        });
                });

            modelBuilder.Entity("SGVE_api.Models.Produtos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID_PRODUTO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<float?>("Custo")
                        .IsRequired()
                        .HasColumnType("real")
                        .HasColumnName("D_CUSTO");

                    b.Property<DateTime>("Data_Cadastro")
                        .HasColumnType("datetime2")
                        .HasColumnName("DT_CADASTRO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("V_DESCRICAO");

                    b.Property<int>("Id_Fornecedor")
                        .HasColumnType("int")
                        .HasColumnName("FK_ID_FORNECEDOR");

                    b.Property<int>("Id_Tipo")
                        .HasColumnType("int")
                        .HasColumnName("FK_ID_TIPO");

                    b.Property<string>("Marca")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("V_MARCA");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("V_NOME");

                    b.Property<float?>("Preco")
                        .IsRequired()
                        .HasColumnType("real")
                        .HasColumnName("D_PRECO");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("I_QUANTIDADE");

                    b.HasKey("Id");

                    b.ToTable("TB_PRODUTO");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            Custo = 1.5f,
                            DataCadastro = new DateTime(2023, 6, 16, 20, 25, 3, 500, DateTimeKind.Local).AddTicks(5885),
                            Descricao = "Bolacha sabor Morango",
                            IdFornecedor = 2,
                            IdTipo = 2,
                            Marca = "Trakinas",
                            Nome = "Bolacha Trakinas",
                            Preco = 0.5f,
                            Quantidade = 10
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
