/*DROP PROCEDURE PROC_LOGIN_FUNC;*/
DELIMITER $$

CREATE PROCEDURE PROC_LOGIN_FUNC(EMAIL VARCHAR(50), SENHA VARCHAR(20)) 
BEGIN	
		SELECT FK_COD_CARGO, CPF_FUNC, NOME_FUNC, DATA_DESLIGAMENTO FROM FUNCIONARIO WHERE EMAIL_FUNC = EMAIL AND SENHA_FUNC = SENHA;
END $$
DELIMITER ;